---
title: "LimNut_200N_nonSucr"
author: "Iván Martín Martín"
date: "10/3/2021"
output: pdf_document
---

Note that for this configuration there is no equivalent M9200N with sucrose in initial values of 100 mM.


## 1. Quick Summary of configurations

* 30 cases had SD < (0.1)·(`avgfitness`) (considered OK).
* 30 cases had SD > (0.1)·(`avgfitness`).
* 40 cases had SD > (0.1)·(`avgfitness`) and they also raised a ZeroDivisionError. In 37 of these cases, *E.coli* was finally exhausted, while in the remaining 3 it was *P.putida* which was exhausted. In many of these cases, naringenin production was disproportionate.

* Number of configurations with acceptable SD and final [NH4+] (mM) = 0: 9 in 30
* Number of configurations with acceptable SD and final death effect: 20 in 30
* Number of configurations with acceptable or non-acceptable SD and final death effect: 49 in 60

**The death effect is present, even under no carbon source (sucrose) limitation**.

## 2. Analysis for fitness ranks

**Fitness ranks** (mM / gL^-1^):

* **1**: (0, 6). 12 values.
* **2**: (6, 11). 11 values.
* **3**: (20, 40). 4 values.
* **4**: (95, 115). 3 values.


**DeadInitCycle**: for ranks n.1 (0, 6) and n.2 (6, 11), the *death effect* started in a cycle ranging from 80-210 and 60-180, respectively. However, in the last two ranks, there were 3 in 12 values and 4 in 11 values, in which this effect did not happened, respectively. In rank n.3 (20, 40), the *death effect* happened in 1 of 4 cases, starting in cycle 99. Finally, in rank n.4 (95, 115) this effect happened for the three values, starting between cycles 60 to 100.

**FinalNH4**: in rank n.1 (0, 6), $NH_{4}$ was exhausted only in 3 of 12 values; in the remaining cases, final values were between 10 to 110 mM. In rank n.2 (6, 11), $NH_{4}$ was exhausted in 5 of 11 values; in the remaining cases, final concentrations were between 90 and 145 mM. In rank n.3 (20, 40), $NH_{4}$ was exhausted in 1 of 4 cases, and the remaining values were above 100 mM. In rank n.4 (95, 115), there were two values around 60 mM, and one value around 10 mM.

**FinalPi**: final $P_{i}$ concentration was variable within the different ranks.

- In rank n.1 (0, 6), this final concentration was 0 for 9 in 12 values; around the initial concentration for 2 values; and higher than initially for 1 case (+10 mM).
- In rank n.2 (6, 11), final $P_{i}$ was 0 or near 0 in 7 cases; around 55 mM and 70 mM in two other cases; and there were two additional outliers with final $P_{i}$ of 600 and 700 mM.
- In rank n.3 (20, 40), there were two points around initial levels and two other points in 0 mM.
- In rank n.4 (95, 115), all 3 values were near 0.

**FinalSucr**: final sucrose concentration was variable within the different ranks.

- In rank n.1 (0, 6), sucrose final concentration ranged from 900 to 100 mM (three different groups of points).
- In rank n.2 (6, 11), sucrose final concentration ranged from 900 to 100 mM (three different groups of points), certain dispersion.
- In rank n.3 (20, 40), there were three points around 900 mM (final sucrose) and one point around 300 mM.
- In rank n.4 (95, 115), all 3 values were near 0.


## 3. Analysis for naringenin production ranks

**Naringenin production ranks** (mM):

* **1**: (0, 8). 13 values.
* **2**: (10, 16). 3 values.
* **3**: (25, 35). 4 values.
* **4**: (35, 55). 4 values.
* **5**: (60, 85). 2 values.
* **6**: (120, 146). 4 values.


**DeadInitCycle**: 
- In rank n.1 (0, 8), there was 1 point with no *death effect*. In the remaining 12, this effect started at different cycles, from 60 to 210.
- In rank n.2 (10, 16), there was 1 point with no *death effect*. In the remaining 2, this effect started at cycles 120 or 130. 
- In rank n.3 (25, 35), there were 2 points with no *death effect*. In the remaining 2, this effect started at cycles 110 or 120. 
- In rank n.4 (35, 55), there were 3 points with no *death effect*. In the remaining one, this effect started at cycle 100.
- In rank n.5 (60, 85), there was 1 point with no *death effect*. In the remaining one, this effect started at cycle 100.
- In rank n.6 (120, 146), there were 2 points with no *death effect*. In the remaining two, this effect started at cycles 65 or 100.

**FinalNH4**: 
- In rank n.1 (0, 8), $NH_{4}$ was exhausted in 4 of 12 values; in the remaining cases, final values were between 10 to 145 mM.
- In rank n.2 (10, 16), $NH_{4}$ was exhausted in 2 of 3 values; in the remaining case, $NH_{4}$ was around 100 mM.
- In rank n.3 (25, 35), $NH_{4}$ was exhausted in 2 cases and remained in 100 mM in 2 other cases.
- In rank n.4 (35, 55), $NH_{4}$ was exhausted in 3 cases and remained in 100 mM in one other case.
- In rank n.5 (60, 85), there was 1 point with final $NH_{4}$ in 60 mM and another point with 130 mM.
- In rank n.6 (120, 146), final $NH_{4}$ were 10, 60, 100 and 120 mM.

**FinalPi**: final $P_{i}$ concentration was variable within the different ranks.

- In rank n.1 (0, 8), this final concentration was 0 for 9 in 12 values; around 10 mM for 2 values; and higher than initially for 1 case (+10 mM).
- In rank n.2 (10, 16), final $P_{i}$ was 0 in 2 cases, and around 80 mM in one case.
- In rank n.3 (25, 35), there were two points around initial levels and two other points in 0 mM.
- In rank n.4 (35, 55), there was 1 point in 0 mM, 1 point around initial values and two outliers in 600 or 700 mM.
- In rank n.5 (60, 85), both values were near 0.
- In rank n.6 (120, 146), there were 2 points around 0 mM and 2 points around initial values.

**FinalSucr**: final sucrose concentration was variable within the different ranks.

- In rank n.1 (0, 8), final sucrose ranged from 900 to 0 mM.
- In rank n.2 (10, 16), final sucrose was around 900 mM in one case and around 200 mM in a different case.
- In rank n.3 (25, 35), final sucrose was ~ 900 mM in two cases, around 600 mM in one case, and around 300 mM in another case.
- In rank n.4 (35, 55), sucrose concentration was around 900-850 mM in three cases and around 300 mM in the remaining one.
- In rank n.5 (60, 85), final sucrose was ~ 900 mM for one point and 0 mM for the other one.
- In rank n.6 (120, 146), final sucrose was ~ 900 mM for two points and 0 mM for the other two.




































